#!/usr/bin/env bash

set -euo pipefail


SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ACT_SECRETS_FILE="$SCRIPT_DIR/.secrets"

mkdir -p "$(dirname "$ACT_SECRETS_FILE")"

cat <<EOF > "$ACT_SECRETS_FILE"
SNOWFLAKE_PASSWORD="$SNOWFLAKE_PASSWORD"
SNOWFLAKE_USER="$SNOWFLAKE_USER"
SNOWFLAKE_ACCOUNT="$SNOWFLAKE_ACCOUNT"
SNOWFLAKE_HOST="$SNOWFLAKE_HOST"
EOF

chmod 600 "$ACT_SECRETS_FILE"